name: CI tests

# trigger
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Prepare python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ hashFiles('**/.ci_pip_reqs.txt') }}-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r .ci_pip_reqs.txt
        pip install -e .
    - name: Run tests
      run: |
        python -m flake8 \
          --exclude=build,doc,tmp,_model.py,conversion_modified_pysb.py,conversion_pysb.py \
          --extend-ignore=F403,F405
        pytest test
